
package ma.fstt.ws.histcarburant;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "HistCarburantJpa", targetNamespace = "http://Ws.fstt.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HistCarburantJpa {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateHistCarburant", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.UpdateHistCarburant")
    @ResponseWrapper(localName = "updateHistCarburantResponse", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.UpdateHistCarburantResponse")
    @Action(input = "http://Ws.fstt.ma/HistCarburantJpa/updateHistCarburantRequest", output = "http://Ws.fstt.ma/HistCarburantJpa/updateHistCarburantResponse")
    public void updateHistCarburant(
        @WebParam(name = "arg0", targetNamespace = "")
        HistCarburant arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteHistCarburant", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.DeleteHistCarburant")
    @ResponseWrapper(localName = "deleteHistCarburantResponse", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.DeleteHistCarburantResponse")
    @Action(input = "http://Ws.fstt.ma/HistCarburantJpa/deleteHistCarburantRequest", output = "http://Ws.fstt.ma/HistCarburantJpa/deleteHistCarburantResponse")
    public void deleteHistCarburant(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addHistCarburant", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.AddHistCarburant")
    @ResponseWrapper(localName = "addHistCarburantResponse", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.AddHistCarburantResponse")
    @Action(input = "http://Ws.fstt.ma/HistCarburantJpa/addHistCarburantRequest", output = "http://Ws.fstt.ma/HistCarburantJpa/addHistCarburantResponse")
    public void addHistCarburant(
        @WebParam(name = "arg0", targetNamespace = "")
        HistCarburant arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ma.fstt.ws.histcarburant.HistCarburant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHistCarburants", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.GetHistCarburants")
    @ResponseWrapper(localName = "getHistCarburantsResponse", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.GetHistCarburantsResponse")
    @Action(input = "http://Ws.fstt.ma/HistCarburantJpa/getHistCarburantsRequest", output = "http://Ws.fstt.ma/HistCarburantJpa/getHistCarburantsResponse")
    public List<HistCarburant> getHistCarburants();

    /**
     * 
     * @param sQLDate
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrices", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.GetPrices")
    @ResponseWrapper(localName = "getPricesResponse", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.GetPricesResponse")
    @Action(input = "http://Ws.fstt.ma/HistCarburantJpa/getPricesRequest", output = "http://Ws.fstt.ma/HistCarburantJpa/getPricesResponse")
    public List<String> getPrices(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.sql.Date sQLDate);

    /**
     * 
     * @param arg0
     * @return
     *     returns ma.fstt.ws.histcarburant.HistCarburant
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "trouverById", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.TrouverById")
    @ResponseWrapper(localName = "trouverByIdResponse", targetNamespace = "http://Ws.fstt.ma/", className = "ma.fstt.ws.histcarburant.TrouverByIdResponse")
    @Action(input = "http://Ws.fstt.ma/HistCarburantJpa/trouverByIdRequest", output = "http://Ws.fstt.ma/HistCarburantJpa/trouverByIdResponse")
    public HistCarburant trouverById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
