
package ma.fstt.ws.histcarburant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "HistCarburantJpaImpService", targetNamespace = "http://Ws.fstt.ma/", wsdlLocation = "http://localhost:7777/ws/HistCarburant?wsdl")
public class HistCarburantJpaImpService
    extends Service
{

    private final static URL HISTCARBURANTJPAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException HISTCARBURANTJPAIMPSERVICE_EXCEPTION;
    private final static QName HISTCARBURANTJPAIMPSERVICE_QNAME = new QName("http://Ws.fstt.ma/", "HistCarburantJpaImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/ws/HistCarburant?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HISTCARBURANTJPAIMPSERVICE_WSDL_LOCATION = url;
        HISTCARBURANTJPAIMPSERVICE_EXCEPTION = e;
    }

    public HistCarburantJpaImpService() {
        super(__getWsdlLocation(), HISTCARBURANTJPAIMPSERVICE_QNAME);
    }

    public HistCarburantJpaImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HISTCARBURANTJPAIMPSERVICE_QNAME, features);
    }

    public HistCarburantJpaImpService(URL wsdlLocation) {
        super(wsdlLocation, HISTCARBURANTJPAIMPSERVICE_QNAME);
    }

    public HistCarburantJpaImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HISTCARBURANTJPAIMPSERVICE_QNAME, features);
    }

    public HistCarburantJpaImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HistCarburantJpaImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HistCarburantJpa
     */
    @WebEndpoint(name = "HistCarburantJpaImpPort")
    public HistCarburantJpa getHistCarburantJpaImpPort() {
        return super.getPort(new QName("http://Ws.fstt.ma/", "HistCarburantJpaImpPort"), HistCarburantJpa.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HistCarburantJpa
     */
    @WebEndpoint(name = "HistCarburantJpaImpPort")
    public HistCarburantJpa getHistCarburantJpaImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Ws.fstt.ma/", "HistCarburantJpaImpPort"), HistCarburantJpa.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HISTCARBURANTJPAIMPSERVICE_EXCEPTION!= null) {
            throw HISTCARBURANTJPAIMPSERVICE_EXCEPTION;
        }
        return HISTCARBURANTJPAIMPSERVICE_WSDL_LOCATION;
    }

}
