
package ma.fstt.ws.station;

import java.net.MalformedURLException;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "StationJpaImpService", targetNamespace = "http://Ws.fstt.ma/", wsdlLocation = "http://localhost:7777/ws/Station?wsdl")
public class StationJpaImpService
    extends Service
{

    private final static URL STATIONJPAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException STATIONJPAIMPSERVICE_EXCEPTION;
    private final static QName STATIONJPAIMPSERVICE_QNAME = new QName("http://Ws.fstt.ma/", "StationJpaImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/ws/Station?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATIONJPAIMPSERVICE_WSDL_LOCATION = url;
        STATIONJPAIMPSERVICE_EXCEPTION = e;
    }

    public StationJpaImpService() {
        super(__getWsdlLocation(), STATIONJPAIMPSERVICE_QNAME);
    }

    public StationJpaImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATIONJPAIMPSERVICE_QNAME);
    }

    public StationJpaImpService(URL wsdlLocation) {
        super(wsdlLocation, STATIONJPAIMPSERVICE_QNAME);
    }

    public StationJpaImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATIONJPAIMPSERVICE_QNAME);
    }

    public StationJpaImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StationJpaImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns StationJpa
     */
    @WebEndpoint(name = "StationJpaImpPort")
    public StationJpa getStationJpaImpPort() {
        return super.getPort(new QName("http://Ws.fstt.ma/", "StationJpaImpPort"), StationJpa.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StationJpa
     */
    @WebEndpoint(name = "StationJpaImpPort")
    public StationJpa getStationJpaImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Ws.fstt.ma/", "StationJpaImpPort"), StationJpa.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATIONJPAIMPSERVICE_EXCEPTION!= null) {
            throw STATIONJPAIMPSERVICE_EXCEPTION;
        }
        return STATIONJPAIMPSERVICE_WSDL_LOCATION;
    }

}
